alias aliases='$EDITOR ~/.bash_aliases'
alias l='ls -lhF --color=auto'
alias ls='ls -h --color=auto'
alias lsd='ls -d */'
alias ..='cd ..'
alias potrace='potrace -s'
alias hello='ping 192.168.1.1'
alias startx='TMUX= exec $(which startx)'
alias tmuxc='~/config/session-scripts/tmux-client.sh'
alias zypper='zypper --no-refresh'

alias brightscreen='redshift -x'
alias dimscreen='redshift -o -O3000'
alias darkscreen='redshift -o -O1500'

alias mrst='mr -j5 st | less'
alias MPLAB='cd ~/.wine/drive_c/Program\ Files/Microchip/MPLAB\ IDE/Core/; wine MPLAB.exe'

alias eshell='emacsclient --eval "(eshell t)"'

#Games
alias homeworld2='cd ~/.wine/drive_c/Program\ Files/Sierra/Homeworld2/Bin/Release/; wine Homeworld2.exe -nopbuffer'
alias homeworld='cd ~/.wine/drive_c/Sierra/Homeworld/; wine homeworld.exe /dsoundCoop'
alias fh='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 1942/; wine BF1942.exe +game fh'
alias xwwii='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 1942/; wine BF1942.exe +game xwwii'
alias bf2='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 2/; wine BF2.exe'
alias fh2='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 2/; wine FH2.exe'
alias stbc='cd ~/.wine/drive_c/Program\ Files/Activision/Bridge\ Commander; wine stbc.exe'
alias chwinedir='cd ~/.wine/drive_c/'
alias dwarf='cd ~/games/dwarf/;./df'
