alias aliases='$EDITOR ~/.bash_aliases'
alias l='ls -lhF --color=auto'
alias ls='ls -h --color=auto'
alias ..='cd ..'
alias potrace='potrace -s'
alias hello='ping 192.168.1.1'
alias startx='exec startx'
alias tmuxc='~/config/bin/tmux-client.sh'

alias MPLAB='cd ~/.wine/drive_c/Program\ Files/Microchip/MPLAB\ IDE/Core/; wine MPLAB.exe'

#Games
alias homeworld2='cd ~/.wine/drive_c/Program\ Files/Sierra/Homeworld2/Bin/Release/; wine Homeworld2.exe -nopbuffer'
alias homeworld='cd ~/.wine/drive_c/Sierra/Homeworld/; wine homeworld.exe /dsoundCoop'
alias fh='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 1942/; wine BF1942.exe +game fh'
alias xwwii='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 1942/; wine BF1942.exe +game xwwii'
alias bf2='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 2/; wine BF2.exe'
alias fh2='cd ~/.wine/drive_c/Program\ Files/EA\ GAMES/Battlefield\ 2/; wine FH2.exe'
alias stbc='cd ~/.wine/drive_c/Program\ Files/Activision/Bridge\ Commander; wine stbc.exe'
alias chwinedir='cd ~/.wine/drive_c/'
alias dwarf='cd ~/games/dwarf/;./df'
